---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r}
setwd("c:/Data Science/RepData")
activity <- read.csv(activity.csv)
numbersteps <- aggregate(steps~date,data=activity,sum,na.rm=TRUE)
```

## What is mean total number of steps taken per day?
```{r}
barplot(numbersteps$steps, names.arg = numbersteps$date)
mean(numbersteps$steps)
median(numbersteps$steps)
```

## What is the average daily activity pattern?
```{r}
library(ggplot2)
average <- aggregate(x=list(steps=activity$steps), by=list(interval=activity$interval), FUN=mean, na.rm=TRUE)
ggplot(data=average, aes(x=interval, y=steps)) + geom_line() + xlab("5-minute interval") + ylab("average number of steps taken")
average[which.max(average$steps),]
```

## Imputing missing values
```{r}
missing <- is.na(activity$steps)
sum(missing)
activity_fill <- activity
activity_fill$steps[which(is.na(activity_fill$steps))] <- tapply(activity_fill$steps, activity_fill$interval, mean, na.rm=T, simplify=F )
activity_fill$steps <- as.vector(activity_fill$steps, mode="numeric")
library("dplyr")
daily_activity_fill <- activity_fill %>% group_by(date) %>% summarise( numbersteps = sum(steps, na.rm=T))
library("ggplot2")
plot3 <- ggplot(daily_activity_fill, aes(date, numbersteps)) + geom_histogram(stat="identity")+ theme(axis.text.x= element_text(size=6, angle=90, vjust=1))
print(plot3)
```

## Are there differences in activity patterns between weekdays and weekends?

